allure.version=2.30.0
# Default = true
allure.automaticallyOpen=true
# Default = true, Add the last error to the report
allure.accumulateHistory=true
# Default = true
allure.accumulateReports=false
# Default = true
allure.cleanResultsDirectory=true
# Default = false
allure.generateArchive=false
# logo url for allure report
allure.customLogo=https://dentolize.s3.eu-central-1.amazonaws.com/4f02c89f-4014-4bf7-89a5-7c1e1c3fbc97/images/cca9e4fb-ab72-4ac4-baf1-1912a1ec8d4c.png
# allure report title
allure.customTitle=Dentolize - Test Automation
