###################################################
#####  Properties
###################################################
propertiesFolderPath_CI=
propertiesFolderPath=src/main/resources/properties/
dynamicObjectRepositoryPath=src/main/resources/dynamicObjectRepository/
testDataFolderPath=src/test/resources/testDataFiles/
downloadsFolderPath=src/test/resources/downloadFiles/
allureResultsFolderPath=allure-results/
extentReportsFolderPath=extent-reports/
executionSummaryReportFolderPath=execution-summary/
PerformanceReportFolderPath=performanceReport/
video.folder=allure-results/videos
applitoolsApiKey=
servicesFolderPath=src/test/resources/META-INF/services/
##########################  Environment   ########################
#### Development Environment
devUrl=https://my.dentope.com/
qaUrl=https://qa.dentope.com/
prodUrl=https://my.dentolize.com/
#### API ####
devApiUrl=https://api.dentope.com/
qaApiUrl=https://qapi.dentope.com/
prodApiUrl=https://api.dentolize.com/
######################### Path - services  ########################################
loginPage=auth/login
patientsPage=patients
labOrdersPage=orders
# finances
expensesPage=finances/expenses
incomesPage=finances/incomes
# inventory
masterInventoryPage=inventory/master
branchInventoryPage=inventory/inventories
# Associates
labsPage=associates/labs
suppliersPage=associates/suppliers
insuranceCompaniesPage=associates/insurance-companies
# settings
branchesPage=settings/branches
usersPage=settings/users
monthlyExpensesPage=settings/monthly-expenses
proceduresPage=settings/procedures
conditionsPage=settings/conditions
medicalOptionsPage=settings/medicals
clinicalOptionsPage=settings/clinical
noteTemplatesPage=settings/noteTemplates
medicationsPage=settings/medications
prescriptionTemplatesPage=settings/templates
patientRemindersPage=settings/patient-reminders
freeFormPage=settings/forms
tasksPage=settings/tasks
smsPage=settings/messages
# Logs
appointmentsPage=logs/created-appointments
operationsPage=logs/operations
prescriptionsPage=logs/prescriptions
notesPage=logs/notes
communicationsPage=logs/communications
######################### Path - TestData Files  ########################################
## Auth ##
loginJsonData=src/test/resources/testDataFiles/login/login.json
## Settings ##
settingsData=src/test/resources/testDataFiles/settings.xlsx
## Associates ##
associatesData=src/test/resources/testDataFiles/associates.xlsx
## Inventory ##
inventoryData=src/test/resources/testDataFiles/inventory.xlsx
## Patients ##
patientsData=src/test/resources/testDataFiles/patients.xlsx
patientsApisJson=src/test/resources/testDataFiles/patients/patientsApis.json
appointmentsApiJson=src/test/resources/testDataFiles/appointments/appointmentsApis.json
##################### success message #####################
successMessages=src/test/resources/testDataFiles/successMessage/successMessage_EN.json
#successMessages=src/test/resources/testDataFiles/successMessage/successMessage_AR.json
##################### config.json #####################
configData=src/test/resources/config.json
###################################################
##### END of Properties File
###################################################